### ISSUE TITLE
403 and 500 Errors Mismatching Endpoints

### ISSUE THREAD

**Issue by Wamy-Dev** [abhinavk99/jikanpy#111]
I keep on getting:

HTTP 503 - status=403, type=BadResponseException, message=Jikan failed to connect to MyAnimeList.net. MyAnimeList.net may be down/unavailable, refuses to connect or took too long to respond., error=403 on https://myanimelist.net/anime/1143/_/episode?offset=0 for id=1143, endpoint=anime

when trying to episodes for an Anime, Maybe there is something mismatching with the endpoints in the code?

**Comment by Chris-Peterson444** [comment]
This looks like an issue on Jikan's side. Can you tell me what anime id so I can recreate this?

**Comment by Wamy-Dev** [comment]
There is a whole list of them. Like it failed on every single request for the 400 or anime I had. I made sure to keep myself under the ratelimit.  Here is a few, I didn't feel like copying and pasting all of it.

37619
33685
1586

**Comment by Chris-Peterson444** [comment]
I'm assuming you're doing something like:
```python
api = Jikan()
ret = api.anime(3914, extension='episodes')
```
I'm not getting any errors on these anime, but there is suspiciously no data. When I pull `anime/full` on the last two IDs in your list they do show 1 and 2 episodes. 

The extra `/_/` in the URL from your error looks like the problem. If I take it out, it loads the correct page on MAL. I'll see about opening an issue with jikan

**Comment by Chris-Peterson444** [comment]
Ah if I do `anime/characters` I do get some 504 and 500 errors

**Comment by Wamy-Dev** [comment]
Yeah it happens consistently in both endpoints. Doesnt happen in Anime/Full at least, but I havent tried anything else other than those 3.

**Comment by Chris-Peterson444** [comment]
It looks like it's fixed but @Wamy-Dev let me know if you have more issues before we close this

**Comment by Wamy-Dev** [comment]
Got it once or twice more after that. 

`HTTP 500 - status=500, type=TransportException, message=Request to MyAnimeList.net has failed. The upstream server has returned a non-successful status code., error=Unsupported response code in HTTP response for "https://myanimelist.net/anime/1832/_/characters". for id=1832, endpoint=anime`

Not as many times as before though.

**Comment by Wamy-Dev** [comment]
https://github.com/jikan-me/jikan-rest/issues/400 was resolved here.
