### ISSUE TITLE
Question: Get random anime of a specific genre

### ISSUE THREAD

**Issue by tsukki9696** [abhinavk99/jikanpy#113]
I was wondering if it's possible to get a random anime that belongs to a specific genre _(like getting a random Shounen anime)_ since `jikan.random()` doesn't have any parameters related to that. Is there any hacky way to implement something like that?

**Comment by Chris-Peterson444** [comment]
Unfortunately `jikan.random()` simply wraps [/random](https://docs.api.jikan.moe/#tag/random) from Jikan, which doesn't take any input filters. For example [/random/anime](https://docs.api.jikan.moe/#tag/random/operation/getRandomAnime) just returns *any* anime (although it might be limited SFW results only). You might want to do something like: use `jikan.search` to grab a handful of resulting animes that match what you want, and randomly grab from that set. 

Something hacky like this is what I might do (I didn't include it in this example, but don't forget to rate limit):
```python
import random
from jikanpy import Jikan
SHOUNEN_ID = 27 # You can find these in the /genres/anime endpoint
api = Jikan()
anime_set: dict[str, dict] = dict() # would use a set directly, but the anime comes back as a dict (unhashable)

for i in range(10):
    response = api.search(search_type='anime', query='', page=i+1, parameters={'genres':SHOUNEN_ID})
    for anime in response['data']:
         anime_set[anime['title']] = anime

random_anime_title = random.choice(list(anime_set.keys()))

```

**Comment by tsukki9696** [comment]
Yeah this is pretty much what I needed. Gonna keep in mind to add a rate limit when I implement this in my code, thank you!
