### ISSUE TITLE
JSONDecodeError: Expecting Value: line 1 column 1 (char 0) in Jikanpy

### ISSUE THREAD

**Issue by Ari24-cb24** [abhinavk99/jikanpy#77]
Hey, I got a problem, I cant call the function `jikan.anime(malID)` anymore. The following exception happens every time now:

File "/home/pi/Hosting/-----/commands/mal.py", line 13, in getInfosFromID
    r = jk.anime(int(malID))
  File "/home/pi/.local/lib/python3.7/site-packages/jikanpy/jikan.py", line 123, in anime
    return self._get("anime", id, extension, page)
  File "/home/pi/.local/lib/python3.7/site-packages/jikanpy/jikan.py", line 91, in _get
    return self._wrap_response(response, url, id=id, endpoint=endpoint)
  File "/home/pi/.local/lib/python3.7/site-packages/jikanpy/jikan.py", line 65, in _wrap_response
    json_response = response.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Could someone plz help me? 
Thanks

**Comment by abhinavk99** [comment]
I think it's because Jikan API isn't really working right now as MAL blocked the servers that the Jikan API works on. The Python wrapper is likely unable to decode the response from the API is it's not in JSON format because the data isn't getting returned right.

**Comment by Ari24-cb24** [comment]
Ah, thank you very much. Do you have any idea when this is gonna work again?

**Comment by abhinavk99** [comment]
I'm not sure, it's already been a day or 2. I think Nekomata, the creator of Jikan, is working on caching data so the Jikan servers don't have to access MAL. Also, make sure you're on the newest version of Jikanpy, v4.1.0, if you aren't already.

**Comment by abhinavk99** [comment]
By the way, can you send me the snippet of code that is causing the error? I'm going to try to update Jikanpy so that it shows a more human readable exception when this happens.

**Comment by Ari24-cb24** [comment]
Yeah, actually, this snippet is build in my discord bot

**Comment by Ari24-cb24** [comment]
so, this is the full code of my command ( https://pastebin.com/k7dNhz0g )
And the exception appears at line 13, when i try to get some Anime informations from the malID

**Comment by abhinavk99** [comment]
Thanks, I'll look into this.

**Comment by abhinavk99** [comment]
Can you give me some MAL IDs that cause the exception? I know it must be late for you in Germany, so feel free to send them whenever you're available.

**Comment by abhinavk99** [comment]
Hmm, since caching is in process, the actually issue might be that you've been IP-banned by Jikan. Try accessing this URL: `https://api.jikan.moe/v3/anime/[put MAL id in here without the brackets]` and see what it says. If you're actually banned, you can join the [Discord server](https://discord.gg/PpzHQvu) and ask Nekomata to unban you.

**Comment by Ari24-cb24** [comment]
Okay, so it gave me on my computer a json output and also the right stuff.
Ill also try it on my Raspberrypi cauz my bot is currently running on this pi.

Btw, i tried the MAL ID from Acchi Kocchi that hasnt worked on my discord bot (12291)

**Comment by Ari24-cb24** [comment]
Okay, so on my raspberrypi it also gives me some json output that seems to be the right stuff
Could it be that there is a maximum requests?

**Comment by abhinavk99** [comment]
I put the code in your pastebin link into a python file and ran `getInfosFromID(22199)` from my console and it worked. I'm sorry but I'm not really sure what the issue could be if it's just Akame ga Kill that isn't working.

**Comment by Ari24-cb24** [comment]
So, first of all, an error appears at nb. 4:
`ImportError: No module named pathlib`
I installed pathlib with py3 and the same error appears. After I installed pathlib with py2 the following exception happend:

`File "/home/pi/Hosting/Tendo/jikanpy/setup.py in line 5 in <module>`
`README = (HERE / "README.md").read_text()`
`AttributeError: "PosixPath" object has no attribute 'read_text'`

**Comment by Ari24-cb24** [comment]
> I put the code in your pastebin link into a python file and ran `getInfosFromID(22199)` from my console and it worked. I'm sorry but I'm not really sure what the issue could be if it's just Akame ga Kill that isn't working.

Yeah, so, I also tried it with Acchi Kocchi but the same exception still happens

**Comment by abhinavk99** [comment]
Wait, is your bot written in Python 2? Jikanpy only supports 3.6 and up.

**Comment by Ari24-cb24** [comment]
My bot is currently written in Python3 and my screen session also runs Python3

**Comment by abhinavk99** [comment]
To be honest, I have no clue what the error could be. Maybe try using requests instead of jikanpy and doing the below in `getInfosFromID()` instead of `r = jk.anime(int(malID))`:

```python
# install requests and simplejson using pip
# Remember to import requests and simplejson at the top of your file
r = requests.get('https://api.jikan.moe/v3/anime/' + int(malID))
try:
    r = r.json()
except simplejson.JSONDecodeError:
    # You can see the raw HTTP response text with this
    raise Exception(r.text)
```

**Comment by Ari24-cb24** [comment]
Okay, that was really a good idea so i got a better exception.
The same exception as above + this:

  File "/home/pi/Hosting/Tendo/commands/mal.py", line 18, in getInfosFromID
    raise Exception(r.text)
Exception: <html>
<head><title>429 Too Many Requests</title></head>
<body>
<center><h1>429 Too Many Requests</h1></center>
<hr><center>nginx</center>
</body>
</html>

**Comment by abhinavk99** [comment]
Yeah, that means you're getting rate limited.

**Comment by Ari24-cb24** [comment]
Yeah, as i said before, i loop through my mal ID's and get for every anime an url and the name of the anime (picture)
![image](https://user-images.githubusercontent.com/56089155/84327493-bd19c380-ab7f-11ea-8226-2f3d68d4d17c.png)

**Comment by abhinavk99** [comment]
Based on this, https://jikan.docs.apiary.io/#introduction/information/rate-limiting, the max is 30 requests/minute and 2 requests/second. Use something like `time.sleep()` to avoid going over that limit.

**Comment by Ari24-cb24** [comment]
So, https://jikan.docs.apiary.io/#introduction/information/wrappers says:
> You MUST use a delay of 4 (FOUR) SECONDS between each request

do you have an idea, how i can fix this?
I just dont want to add a dealy between every loop segment

**Comment by Ari24-cb24** [comment]
> Based on this, https://jikan.docs.apiary.io/#introduction/information/rate-limiting, the max is 30 requests/minute and 2 requests/second. Use something like `time.sleep()` to avoid going over that limit.

okay, ill try that

**Comment by abhinavk99** [comment]
I'm not sure what you mean. That's a UI thing so it's up to you.

**Comment by abhinavk99** [comment]
Closing since issue has been solved.
