### ISSUE TITLE
schedule()

### ISSUE THREAD

**Issue by fangyman** [abhinavk99/jikanpy#82]
Whenever I try to do .schedule(day="sunday") it throws me an error that says
jikanpy.exceptions.APIException: HTTP 403 - status=403, type=BadResponseException, message=Something went wrong, please try again later, error=403 on https://myanimelist.net/anime/season/schedule for day=sunday, but whenever I do .schedule() it gives the schedule for all seven days. 
Is this error on my end or is their some way to fix this error

**Comment by irfan-dahir** [comment]
Please refer to https://github.com/jikan-me/jikan-rest/issues/123#issuecomment-663598909
