### ISSUE TITLE
A way to search for manga or anime without id number

### ISSUE THREAD

**Issue by gabrigode** [abhinavk99/jikanpy#83]
Theres any way to get a anime or manga without the id number for a random purpose?

**Comment by seanbreckenridge** [comment]
I have a [repo here](https://github.com/seanbreckenridge/mal-id-cache) for that purpose.

**Comment by janvernieuwe** [comment]
You need to search first, then fetch the anime.
```py
    search = jikan.search('anime', ' '.join(search))
    if len(search['results']) == 0:
        return
    anime_id = search['results'][0]['mal_id']
    anime = jikan.anime(anime_id)
```
This is to fetch the first match returned from the search.

**Comment by abhinavk99** [comment]
I'm not sure why you're doing a string join on the search variable, but it looks good apart from that.

**Comment by janvernieuwe** [comment]
yeah I just copied something from a project real quick, just ignore join...

**Comment by abhinavk99** [comment]
Closing since there hasn't been a response. Feel free to reopen.
