### ISSUE TITLE
4.3.2 tag missing on GitHub

### ISSUE THREAD

**Issue by mgorny** [abhinavk99/jikanpy#95]
We use GitHub to fetch sources. Could you please push a new tag we can use?

**Comment by seanbreckenridge** [comment]
havent done one myself before but I think [this](https://github.com/abhinavk99/jikanpy/releases/tag/v4.3.2) did it?

Let me know if theres an issue with that

**Comment by mgorny** [comment]
Yeah, looks good. Thanks!
